version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
      - ./transcriptions:/app/transcriptions
    environment:
      - FLASK_ENV=development
    command: python app.py